---
title: "COIL20 MFA"
output: html_notebook
---


```{r}
setwd("/Users/vanna/Documents/PPD/DATASET")
```


```{r}
library("raster")
library("EMMIXmfa")
library("aricode")
library("OpenImageR")
library("clusterCrit")
library("FactoMineR")
library("R.matlab")
```

#1 IMPORT THE DATASET
```{r}
coil20<- readMat("COIL20.mat")
coil20_data<-coil20$X
true_labels<-as.vector(coil20$Y)
```
#2 MFA ON DATASET
```{r}
mfa_coil20<- mfa(coil20_data, 20, 2,  itmax = 2, nkmeans =2 , nrandom = 2,
tol = 1.e-5, sigma_type = 'common', D_type = 'common', init_clust = NULL,
init_para = NULL, conv_measure = 'diff', warn_messages = TRUE)
```

#3 CLUSTERING

```{r}

mfa_label<-mfa_coil20$clust

coil20_ARI_restult=ARI(true_labels,mfa_label)
print(paste0("ARI: ", coil20_ARI_restult))
coil20_NMI_restult=NMI(true_labels,mfa_label)
print(paste0("NMI: ", coil20_NMI_restult))

```
#4 SEPARABILITY
##4.1 MFA
```{r}
plot(mfa_coil20$Umean,col=true_labels)
```
```{r}
#MFA separabilité
intCriteria(mfa_coil20$Umean,as.integer(coil20$Y),c("Silhouette","Davies_Bouldin"))
```
##4.2 Comparison with PCA
```{r}
pca_coil<-PCA(coil20$X,ncp=2, axes=c(1,2))
plot(pca_coil$ind$coord, col=true_labels)
```


```{r}
#PCA separabilité
intCriteria(pca_coil$ind$coord,as.integer(true_labels),c("Silhouette","Davies_Bouldin"))
```
