---
title: "USPS"
output: html_notebook
---


```{r "setup", include=FALSE}
knitr::opts_knit$set(root.dir = "/Users/vanna/Documents/PPD/DATASET") 
```


```{r}
library("raster")
library("EMMIXmfa")
library("aricode")
library("OpenImageR")
library("clusterCrit")
library("FactoMineR")
library("R.matlab")
```

#1 IMPORT THE DATASET
```{r}
usps<- readMat("USPS.mat")
usps_data<-usps$X
true_labels<-as.vector(usps$y)
```
#2 MFA ON DATASET
```{r}
mfa_usps<- mfa(usps_data, 10, 2,  itmax = 2, nkmeans =2 , nrandom = 2,
tol = 1.e-5, sigma_type = 'common', D_type = 'common', init_clust = NULL,
init_para = NULL, conv_measure = 'diff', warn_messages = TRUE)
mfa_label_usps<-mfa_usps$clust

usps_ARI_restult=ARI(true_labels,mfa_label_usps)
print(paste0("ARI: ", usps_ARI_restult))
usps_NMI_restult=NMI(true_labels,mfa_label_usps)
print(paste0("NMI: ", usps_NMI_restult))

```
```{r}
true_labels

```

#3 CLUSTERING

```{r}

mfa_label_usps<-mfa_usps$clust

usps_ARI_restult=ARI(true_labels,mfa_label_usps)
print(paste0("ARI: ", usps_ARI_restult))
usps_NMI_restult=NMI(true_labels,mfa_label_usps)
print(paste0("NMI: ", usps_NMI_restult))

```
#4 SEPARABILITY
##4.1 MFA
```{r}
plot(mfa_usps$Umean,col=true_labels)
```
```{r}
#MFA separabilité
intCriteria(mfa_usps$Umean,as.integer(usps$y),c("Silhouette","Davies_Bouldin"))
```
##4.2 Comparison with PCA
```{r}
pca_usps<-PCA(usps_data,ncp=5, axes=c(1,2))
plot(pca_usps$ind$coord, col=true_labels)
```


```{r}
#PCA separabilité
intCriteria(pca_usps$ind$coord,as.integer(true_labels),c("Silhouette","Davies_Bouldin"))
```