---
title: "YALE"
output: html_notebook
---



```{r}
setwd("/Users/vanna/Documents/PPD/DATASET")
```


```{r}
library("raster")
library("EMMIXmfa")
library("aricode")
library("OpenImageR")
library("clusterCrit")
library("FactoMineR")
library("R.matlab")
```


#1 IMPORT THE DATASET
```{r}
yale<- readMat("Yale.mat")
yale_data<-yale$X
true_labels<-as.vector(yale$Y)
```
#2 MFA ON DATASET
```{r}
mfa_yale<- mfa(yale_data, 15, 2,  itmax = 4, nkmeans =4 , nrandom = 2,
tol = 1.e-5, sigma_type = 'common', D_type = 'common', init_clust = NULL,
init_para = NULL, conv_measure = 'diff', warn_messages = TRUE)
```
#3 CLUSTERING

```{r}

mfa_label_yale<-mfa_yale$clust

yale_ARI_restult=ARI(true_labels,mfa_label)
print(paste0("ARI: ", yale_ARI_restult))
yale_NMI_restult=NMI(true_labels,mfa_label)le
print(paste0("NMI: ", yale_NMI_restult))

```
#4 SEPARABILITY
##4.1 MFA
```{r}
plot(mfa_coil20$Umean,col=true_labels)
```

```{r}
#MFA separabilité
intCriteria(mfa_coil20$Umean,as.integer(coil20$Y),c("Silhouette","Davies_Bouldin"))
```
##4.2 Comparison with PCA
```{r}
pca_yale<-PCA(yale$X,ncp=2, axes=c(1,2))
plot(pca_yale$ind$coord, col=true_labels)
```

```{r}
#PCA separabilité
intCriteria(pca_yale$ind$coord,as.integer(true_labels),c("Silhouette","Davies_Bouldin"))
```